### PR TITLE
Client README 빌드 내용 추가

### PR DESCRIPTION
**Pull request by howyoujini**
Client README.adoc 을 수정 및 추가하였습니다.

- 안드로이드 빌드 : apk `--split-per-abi` 여부에 따른 다른 점 추가
- ios 빌드 : ipa 빌드를 하기 위한 과정을 상세하게 추가 
- `flutter build ipa` 실행해보면서 생긴 파일들 추가됨

### CODE REVIEW

**Comment by FrancescoJo** [comment]
[client/lib/client_application.dart](https://github.com/sirloin-dev/meatplatform-sandbox/pull/16/files#diff-51a42185bbf028ffabb561a9d4734ed3764b0f780956e24697cf474c5ca6e563)
[client/lib/data/local/seraialised_data.dart]https://github.com/sirloin-dev/meatplatform-sandbox/pull/16/files#diff-5a5936d9fb3e96b0b502a4e2478a6d9f120f5bff5fce3e4637439905d5fee712
[client/lib/screen/bloc_sreen_splash.dart → client/lib/screen/bloc_screen_splash.dart]https://github.com/sirloin-dev/meatplatform-sandbox/pull/16/files#diff-d17e7456627a286e97c712c3ed60c5904e9935778c22f52a17cee621376a9217
[client/lib/screen/screen_splash.dart](https://github.com/sirloin-dev/meatplatform-sandbox/pull/16/files#diff-53129d78e718dc928e188b5ce6784ec6839dd7144975db7ece0e9e7cb7aa7edc)
[client/test/testcase/small/data/remote/http/http_client_test.dart](https://github.com/sirloin-dev/meatplatform-sandbox/pull/16/files#diff-9fbcee2a2cb8cd43219f5e62daf8fb545ba3a7e1ca7c9f199813bd62f000b6be)

**Comment by FrancescoJo** [comment]
xcode gitignore target 을 설정해주세요.

https://stackoverflow.com/questions/21597743/which-files-should-i-ignore-with-git-gitignore-for-an-xcode-5-project

**Review by FrancescoJo — CHANGES_REQUESTED** [review]
수정 필요

**Comment by howyoujini** [comment]
[ gitignore 추가 ] PR 봐주시면 됩니다 !

**Pull request closed without merging**
